### ISSUE TITLE
Lack of Syntax Highlighting

### ISSUE THREAD

**Issue by ASBaumgarten** [atom/language-csharp#12]
Public static classes such as "Console.Writeline" are not highlighted at all, unlike the highlighting in my Xamarin IDE.

![no syntax highlight](https://cloud.githubusercontent.com/assets/7777147/4368469/9ff674d4-42ed-11e4-8571-dce58a318c6e.png)
![syntax highlight](https://cloud.githubusercontent.com/assets/7777147/4368468/9ff034ca-42ed-11e4-9bf0-19059b418091.png)

**Comment by noresjo** [comment]
It would be very nice if this was fixed. Makes the code much more readable to me at least.

**Comment by Nokel81** [comment]
Also would having =/==/+= etc being highlighted

**Comment by damieng** [comment]
We'll never be able to syntax highlight things like Console correctly as we can't tell if it's a namespace or a class because we don't have a full compilation/parsing engine behind us like VS and Xamarin.

There have however been many additions to our highlighting in master which include a lot of areas where we can detect things including casts/new/as, variable names.

Going to close this issue in favor of very specific snippets of code we can or can't enhance upon.
