### ISSUE TITLE
Add Razor support

### ISSUE THREAD

**Issue by kristoforsalmin** [atom/language-csharp#130]
## Summary

Hi there, it'd be nice to add syntax highlighting for [Razor](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/) (cshtml) files.

## Motivation

Razor is very common among web projects written in C#. Just like ERB and Ruby. Atom is somewhat popular among frontenders and it makes perfect sense to include Razor in this package.

## Describe alternatives you've considered

Well, there's a [language-cshtml package](https://github.com/demyte/language-cshtml), but it's no longer supported.

---

Thanks 🙂

**Comment by rsese** [comment]
Thanks for the suggestion!  As mentioned in the issue template, we're unlikely to prioritize new functionality right now unfortunately, especially in cases when the feature could be provided through Atom's customizability (see the discussion in https://github.com/atom/language-csharp/pull/120 since adding Razor support has come up before).  Since this isn't something the team would work on I'll close this out, but thank you again for the idea.
