### ISSUE TITLE
Comment containing { on same line as class member not highlighted correctly

### ISSUE THREAD

**Issue by aroben** [atom/language-csharp#14]
```csharp
class Foo
{
  int bar;//{baz
}
```

The `{` in the comment above causes the comment not to get parsed or highlighted as a comment.

![screen shot 2014-11-21 at 4 12 42 pm](https://cloud.githubusercontent.com/assets/917945/5149678/3d3605aa-7199-11e4-83a3-707636bb8f14.png)

You can see this on github.com, which uses this package for highlighting C#: https://github.com/nilproject/NiL.JS/blob/7dce6bc52733f8f1d9d56ec4b329dcc7e5b4cae8/NiL.JS/Script.cs#L14. This bug was discovered by one of our users.

**Comment by jonorossi** [comment]
I just ran into a similar problem that I suspect might be related, as the grammar shouldn't really have a problem with anything other than a newline in the comment.

![atom_cs_comment_broken](https://cloud.githubusercontent.com/assets/126297/6725959/717d560e-ce5c-11e4-9793-649470f9a45d.png)

I had a look at the grammar, but I don't have time to work out how to edit atom languages just at the moment. I wonder why the `captures` number is 1 rather than 0, is that so the new line isn't included in the token atom matches? I assume the `\n` is optional if the comment is on the last line in the file.
https://github.com/atom/language-csharp/blob/master/grammars/c%23.cson#L189-191

I had a look at the grammar for Java and it works quite different, these problems don't exist if I switch to Java in Atom. Maybe we can just copy that bit from the grammar?

**Comment by 50Wliu** [comment]
Fixed by #36 :sparkles:.
