### ISSUE TITLE
Generic Parameters break method signature parsing

### ISSUE THREAD

**Issue by andycmaj** [atom/language-csharp#50]
Notice how method names with Generic parameters aren't parsed as `entity.name.function.cs`. You can tell because `Register<TEvent>` has no style applied.

Also, Generic parameters aren't recognized in method return-types.

<img width="705" alt="broken method signatures" src="https://cloud.githubusercontent.com/assets/97470/13099370/2fcedc82-d4e6-11e5-9ade-c6c6abfe63bb.png">

sample code:

``` csharp
        // Broken
        public IDisposable Register<TEvent, THandler>()
            where TEvent : IEvent
            where THandler : IEventHandler<TEvent>, new()
        {
        }

        // OK
        public IDisposable Register(Type eventType, IEventHandler handler)
        {
        }

        // Broken
        public IDisposable Register<TEvent>(IEventHandlerFactory handlerFactory) where TEvent : IEvent
        {
        }

        // Returntype broken
        public IDisposable<TEvent, TBar> Register(Type eventType, IEventHandlerFactory handlerFactory)
        {
        }
```

**Comment by damieng** [comment]
Has been fixed in master and should ship in the next beta, here's a screenshot of your code. 

![image](https://cloud.githubusercontent.com/assets/118951/21557987/60cf13f0-cde8-11e6-837b-575de66dbf19.png)

Note that return-types featuring multiple generic arguments are not yet processed correctly and we're going to track that in #88
