### ISSUE TITLE
no coloring in function calls

### ISSUE THREAD

**Issue by PierBover** [atom/language-csharp#63]
Is this normal?

![image](https://cloud.githubusercontent.com/assets/226483/14415947/2c096186-ff6a-11e5-96a7-8f9ab776e4cc.png)

Most of the code only uses one color.

**Comment by 50Wliu** [comment]
Probably not.  Does it happen with other syntax themes as well?

**Comment by PierBover** [comment]
Yes.

This is with the Atom Dark syntax theme (the previous screenshot was with One Dark).

![image](https://cloud.githubusercontent.com/assets/226483/14435488/c19a5372-ffdd-11e5-8e0e-85416ad2004d.png)

**Comment by Murriouz** [comment]
Same here.

**Comment by damieng** [comment]
A lot of this is by-design as the syntax highlighting can't distinguish between classes, method calls, property access and variable names because there isn't a compiler behind the scenes. 

The second screenshot exhibits a separate issue where { and } in a string causes it to think the method ends in a similar way to https://github.com/dotnet/coreclr/blob/7b97c58/src/mscorlib/src/System/RtType.cs#L63

**Comment by damieng** [comment]
Hi, a big merge just got put in that adds some additional highlighting in various places such as constraints, generics etc. It should ship in the next beta of Atom.

 I'm going to close this issue in favor of very specific instances where highlighting still doesn't happen.
