### ISSUE TITLE
`private` modifier on getter/setter not highlighted correctly

### ISSUE THREAD

**Issue by Xyene** [atom/language-csharp#99]
It looks like on Github, the `private` modifier on a setter doesn't get highlighted red as it should:

```c#
uint _A;
private uint A
{
    get => _A;
    private set { _A = foo(value);  }
}
```

In a simpler example, it does indeed get highlighted, but perhaps not the right color:
```c#
public uint A { get; private set; }
```

**Comment by jaredmpayne** [comment]
I second this issue.

It looks like the grammar only defines the beginning (up to the opening brace) and end (the closing brace or semicolon) of a property declaration rather than its actual form. Thus, everything inside of it is treated no differently than any other code even though a property has a very unique format compared to other snippets of C# code.

A screenshot of this in action:

![capture](https://user-images.githubusercontent.com/7102870/33272901-a5abbda8-d359-11e7-96be-80e00ac41c20.PNG)

The property grammar according to dotnet:
https://github.com/dotnet/csharplang/blob/master/spec/classes.md#properties

```
property_declaration
    : attributes? property_modifier* type member_name property_body
    ;

property_modifier
    : 'new'
    | 'public'
    | 'protected'
    | 'internal'
    | 'private'
    | 'static'
    | 'virtual'
    | 'sealed'
    | 'override'
    | 'abstract'
    | 'extern'
    | property_modifier_unsafe
    ;

property_body
    : '{' accessor_declarations '}' property_initializer?
    | '=>' expression ';'
    ;

property_initializer
    : '=' variable_initializer ';'
    ;
```
